package com.dsc.qlnt.model;
// Generated Mar 27, 2021 12:16:42 AM by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChuKhuTro generated by hbm2java
 */
@Entity
@Table(name = "chu_khu_tro")
public class ChuKhuTro implements java.io.Serializable {

	private Integer idChuKhuTro;
	private String hoTen;
	private boolean nu;
	private Date namSinh;
	private String sdt;
	private Set<KhuTro> khuTros = new HashSet<KhuTro>(0);

	public ChuKhuTro() {
	}

	public ChuKhuTro(String hoTen, boolean nu, String sdt) {
		this.hoTen = hoTen;
		this.nu = nu;
		this.sdt = sdt;
	}

	public ChuKhuTro(String hoTen, boolean nu, Date namSinh, String sdt, Set<KhuTro> khuTros) {
		this.hoTen = hoTen;
		this.nu = nu;
		this.namSinh = namSinh;
		this.sdt = sdt;
		this.khuTros = khuTros;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_CHU_KHU_TRO", unique = true, nullable = false)
	public Integer getIdChuKhuTro() {
		return this.idChuKhuTro;
	}

	public void setIdChuKhuTro(Integer idChuKhuTro) {
		this.idChuKhuTro = idChuKhuTro;
	}

	@Column(name = "HO_TEN", nullable = false, length = 50)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "NU", nullable = false)
	public boolean isNu() {
		return this.nu;
	}

	public void setNu(boolean nu) {
		this.nu = nu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NAM_SINH", length = 10)
	public Date getNamSinh() {
		return this.namSinh;
	}

	public void setNamSinh(Date namSinh) {
		this.namSinh = namSinh;
	}

	@Column(name = "SDT", nullable = false, length = 50)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuKhuTro")
	public Set<KhuTro> getKhuTros() {
		return this.khuTros;
	}

	public void setKhuTros(Set<KhuTro> khuTros) {
		this.khuTros = khuTros;
	}

}
