package com.dsc.qlnt.model;
// Generated Mar 27, 2021 12:16:42 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KhoangCachId generated by hbm2java
 */
@Embeddable
public class KhoangCachId implements java.io.Serializable {

	private int idTruong;
	private int idKhuTro;

	public KhoangCachId() {
	}

	public KhoangCachId(int idTruong, int idKhuTro) {
		this.idTruong = idTruong;
		this.idKhuTro = idKhuTro;
	}

	@Column(name = "ID_TRUONG", nullable = false)
	public int getIdTruong() {
		return this.idTruong;
	}

	public void setIdTruong(int idTruong) {
		this.idTruong = idTruong;
	}

	@Column(name = "ID_KHU_TRO", nullable = false)
	public int getIdKhuTro() {
		return this.idKhuTro;
	}

	public void setIdKhuTro(int idKhuTro) {
		this.idKhuTro = idKhuTro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KhoangCachId))
			return false;
		KhoangCachId castOther = (KhoangCachId) other;

		return (this.getIdTruong() == castOther.getIdTruong()) && (this.getIdKhuTro() == castOther.getIdKhuTro());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTruong();
		result = 37 * result + this.getIdKhuTro();
		return result;
	}

}
