package com.dsc.qlnt.model;
// Generated Mar 27, 2021 12:16:42 AM by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * KhuTro generated by hbm2java
 */
@Entity
@Table(name = "khu_tro")
public class KhuTro implements java.io.Serializable {
	private Integer idKhuTro;
	private ChuKhuTro chuKhuTro;
	private XaPhuong xaPhuong;
	private String tenKhuTro;
	private String diaChi;
	private double kinhDo;
	private double viDo;
	private Set<KhoangCach> khoangCaches = new HashSet<KhoangCach>(0);
	private Set<LoaiPhong> loaiPhongs = new HashSet<LoaiPhong>(0);
	private int soPhongTrong;

	public KhuTro() {
	}

	public KhuTro(ChuKhuTro chuKhuTro, XaPhuong xaPhuong, String tenKhuTro, String diaChi, double kinhDo, double viDo) {
		this.chuKhuTro = chuKhuTro;
		this.xaPhuong = xaPhuong;
		this.tenKhuTro = tenKhuTro;
		this.diaChi = diaChi;
		this.kinhDo = kinhDo;
		this.viDo = viDo;
	}

	public KhuTro(ChuKhuTro chuKhuTro, XaPhuong xaPhuong, String tenKhuTro, String diaChi, double kinhDo, double viDo,
			Set<KhoangCach> khoangCaches, Set<LoaiPhong> loaiPhongs) {
		this.chuKhuTro = chuKhuTro;
		this.xaPhuong = xaPhuong;
		this.tenKhuTro = tenKhuTro;
		this.diaChi = diaChi;
		this.kinhDo = kinhDo;
		this.viDo = viDo;
		this.khoangCaches = khoangCaches;
		this.loaiPhongs = loaiPhongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_KHU_TRO", unique = true, nullable = false)
	public Integer getIdKhuTro() {
		return this.idKhuTro;
	}

	public void setIdKhuTro(Integer idKhuTro) {
		this.idKhuTro = idKhuTro;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CHU_KHU_TRO", nullable = false)
	public ChuKhuTro getChuKhuTro() {
		return this.chuKhuTro;
	}

	public void setChuKhuTro(ChuKhuTro chuKhuTro) {
		this.chuKhuTro = chuKhuTro;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_XA_PHUONG", nullable = false)
	public XaPhuong getXaPhuong() {
		return this.xaPhuong;
	}

	public void setXaPhuong(XaPhuong xaPhuong) {
		this.xaPhuong = xaPhuong;
	}

	@Column(name = "TEN_KHU_TRO", nullable = false, length = 150)
	public String getTenKhuTro() {
		return this.tenKhuTro;
	}

	public void setTenKhuTro(String tenKhuTro) {
		this.tenKhuTro = tenKhuTro;
	}

	@Column(name = "DIA_CHI", nullable = false, length = 200)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "KINH_DO", nullable = false, precision = 22, scale = 0)
	public double getKinhDo() {
		return this.kinhDo;
	}

	public void setKinhDo(double kinhDo) {
		this.kinhDo = kinhDo;
	}

	@Column(name = "VI_DO", nullable = false, precision = 22, scale = 0)
	public double getViDo() {
		return this.viDo;
	}

	public void setViDo(double viDo) {
		this.viDo = viDo;
	}

	@JsonIgnore
	@OrderBy("id.idTruong ASC")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khuTro",cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<KhoangCach> getKhoangCaches() {
		return this.khoangCaches;
	}

	public void setKhoangCaches(Set<KhoangCach> khoangCaches) {
		this.khoangCaches = khoangCaches;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khuTro")
	public Set<LoaiPhong> getLoaiPhongs() {
		return this.loaiPhongs;
	}

	public void setLoaiPhongs(Set<LoaiPhong> loaiPhongs) {
		this.loaiPhongs = loaiPhongs;
	}

	@Transient
	public int getSoPhongTrong() {
		return soPhongTrong;
	}

	public void setSoPhongTrong(int soPhongTrong) {
		this.soPhongTrong = soPhongTrong;
	}

	@Transient
	public String getFullAddress() {
		return String.format("%s, %s, %s, %s",
				diaChi,
				xaPhuong.getTenXaPhuong(),
				xaPhuong.getQuanHuyen().getTenQuanHuyen(),
				xaPhuong.getQuanHuyen().getTinhTp().getTenTinhTp());
	}

	@Transient
	public String getTenChuKhuTro() {
		return chuKhuTro.getHoTen();
	}

	@Transient
	public Integer getIdChuTro() {
		return chuKhuTro.getIdChuKhuTro();
	}

	@Transient
	public Integer getIdXaPhuong() {
		return xaPhuong.getIdXaPhuong();
	}

	@Transient
	public Integer getIdQuanHuyen() {
		return xaPhuong.getIdQuanHuyen();
	}

	@Transient
	public Integer getIdTinhTp() {
		return xaPhuong.getQuanHuyen().getIdTinhTp();
	}

	@Transient
	public String getSdtChuTro() {
		return chuKhuTro.getSdt();
	}

	@Transient
	public Date getNamSinhChuTro() {
		return chuKhuTro.getNamSinh();
	}

	@Transient
	public boolean isNu() {
		return chuKhuTro.isNu();
	}
}
