package com.dsc.qlnt.model;
// Generated Mar 27, 2021 12:16:42 AM by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", uniqueConstraints = @UniqueConstraint(columnNames = "URL"))
public class Menu implements java.io.Serializable {

	private int idMenu;
	private Menu menuCha;
	private String tenMenu;
	private String url;
	private String icon;
	private boolean hienThi;
	private Set<Menu> menus = new HashSet<Menu>(0);
	private Set<VaiTro> vaiTros = new HashSet<VaiTro>(0);

	public Menu() {
	}

	public Menu(int idMenu, String tenMenu, boolean hienThi) {
		this.idMenu = idMenu;
		this.tenMenu = tenMenu;
		this.hienThi = hienThi;
	}

	public Menu(int idMenu, Menu menu, String tenMenu, String url, String icon, boolean hienThi, Set<Menu> menus,
			Set<VaiTro> vaiTros) {
		this.idMenu = idMenu;
		this.menuCha = menu;
		this.tenMenu = tenMenu;
		this.url = url;
		this.icon = icon;
		this.hienThi = hienThi;
		this.menus = menus;
		this.vaiTros = vaiTros;
	}

	@Id

	@Column(name = "ID_MENU", unique = true, nullable = false)
	public int getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(int idMenu) {
		this.idMenu = idMenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEN_ID_MENU")
	public Menu getMenuCha() {
		return this.menuCha;
	}

	public void setMenuCha(Menu menu) {
		this.menuCha = menu;
	}

	@Column(name = "TEN_MENU", nullable = false, length = 150)
	public String getTenMenu() {
		return this.tenMenu;
	}

	public void setTenMenu(String tenMenu) {
		this.tenMenu = tenMenu;
	}

	@Column(name = "URL", unique = true, length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ICON", length = 200)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "HIEN_THI", nullable = false)
	public boolean isHienThi() {
		return this.hienThi;
	}

	public void setHienThi(boolean hienThi) {
		this.hienThi = hienThi;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuCha")
	@OrderBy("idMenu ASC")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

	@JsonIgnore
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "menus")
	public Set<VaiTro> getVaiTros() {
		return this.vaiTros;
	}

	public void setVaiTros(Set<VaiTro> vaiTros) {
		this.vaiTros = vaiTros;
	}

	public boolean isChild(String url) {
		for (Menu m:menus) {
			if (("/"+m.getUrl()).equalsIgnoreCase(url))
				return true;
		}
		return false;
	}
}
