package com.dsc.qlnt.model;
// Generated Mar 26, 2021 10:06:33 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuanHuyen generated by hbm2java
 */
@Entity
@Table(name = "quan_huyen")
public class QuanHuyen implements java.io.Serializable {

	private Integer idQuanHuyen;
	private TinhTp tinhTp;
	private String tenQuanHuyen;
	private byte[] polygon;
	private Set<XaPhuong> xaPhuongs = new HashSet<XaPhuong>(0);

	public QuanHuyen() {
	}

	public QuanHuyen(TinhTp tinhTp, String tenQuanHuyen) {
		this.tinhTp = tinhTp;
		this.tenQuanHuyen = tenQuanHuyen;
	}

	public QuanHuyen(TinhTp tinhTp, String tenQuanHuyen, byte[] polygon, Set<XaPhuong> xaPhuongs) {
		this.tinhTp = tinhTp;
		this.tenQuanHuyen = tenQuanHuyen;
		this.polygon = polygon;
		this.xaPhuongs = xaPhuongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_QUAN_HUYEN", unique = true, nullable = false)
	public Integer getIdQuanHuyen() {
		return this.idQuanHuyen;
	}

	public void setIdQuanHuyen(Integer idQuanHuyen) {
		this.idQuanHuyen = idQuanHuyen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TINH_TP", nullable = false)
	public TinhTp getTinhTp() {
		return this.tinhTp;
	}

	public void setTinhTp(TinhTp tinhTp) {
		this.tinhTp = tinhTp;
	}

	@Column(name = "TEN_QUAN_HUYEN", nullable = false, length = 150)
	public String getTenQuanHuyen() {
		return this.tenQuanHuyen;
	}

	public void setTenQuanHuyen(String tenQuanHuyen) {
		this.tenQuanHuyen = tenQuanHuyen;
	}

	@Column(name = "POLYGON")
	public byte[] getPolygon() {
		return this.polygon;
	}

	public void setPolygon(byte[] polygon) {
		this.polygon = polygon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quanHuyen")
	public Set<XaPhuong> getXaPhuongs() {
		return this.xaPhuongs;
	}

	public void setXaPhuongs(Set<XaPhuong> xaPhuongs) {
		this.xaPhuongs = xaPhuongs;
	}

}
