package com.dsc.qlnt.model;
// Generated Mar 27, 2021 12:16:42 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GiaThue generated by hbm2java
 */
@Entity
@Table(name = "gia_thue")
public class GiaThue implements java.io.Serializable {

	private Integer idGiaThue;
	private LoaiPhong loaiPhong;
	private long giaThue;
	private Date ngayApDung;

	public GiaThue() {
	}

	public GiaThue(LoaiPhong loaiPhong, long giaThue, Date ngayApDung) {
		this.loaiPhong = loaiPhong;
		this.giaThue = giaThue;
		this.ngayApDung = ngayApDung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_GIA_THUE", unique = true, nullable = false)
	public Integer getIdGiaThue() {
		return this.idGiaThue;
	}

	public void setIdGiaThue(Integer idGiaThue) {
		this.idGiaThue = idGiaThue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_LOAI_PHONG", nullable = false)
	public LoaiPhong getLoaiPhong() {
		return this.loaiPhong;
	}

	public void setLoaiPhong(LoaiPhong loaiPhong) {
		this.loaiPhong = loaiPhong;
	}

	@Column(name = "GIA_THUE", nullable = false, precision = 10, scale = 0)
	public long getGiaThue() {
		return this.giaThue;
	}

	public void setGiaThue(long giaThue) {
		this.giaThue = giaThue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAY_AP_DUNG", nullable = false, length = 10)
	public Date getNgayApDung() {
		return this.ngayApDung;
	}

	public void setNgayApDung(Date ngayApDung) {
		this.ngayApDung = ngayApDung;
	}

}
