package com.dsc.qlnt.model;
// Generated Mar 27, 2021 12:16:42 AM by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * QuanHuyen generated by hbm2java
 */
@Entity
@Table(name = "quan_huyen")
public class QuanHuyen implements java.io.Serializable {

	private Integer idQuanHuyen;
	private TinhTp tinhTp;
	private String tenQuanHuyen;
	private String polygon;
	private Set<XaPhuong> xaPhuongs = new HashSet<XaPhuong>(0);

	public QuanHuyen() {
	}

	public QuanHuyen(TinhTp tinhTp, String tenQuanHuyen) {
		this.tinhTp = tinhTp;
		this.tenQuanHuyen = tenQuanHuyen;
	}

	public QuanHuyen(TinhTp tinhTp, String tenQuanHuyen, String polygon, Set<XaPhuong> xaPhuongs) {
		this.tinhTp = tinhTp;
		this.tenQuanHuyen = tenQuanHuyen;
		this.polygon = polygon;
		this.xaPhuongs = xaPhuongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_QUAN_HUYEN", unique = true, nullable = false)
	public Integer getIdQuanHuyen() {
		return this.idQuanHuyen;
	}

	public void setIdQuanHuyen(Integer idQuanHuyen) {
		this.idQuanHuyen = idQuanHuyen;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TINH_TP", nullable = false)
	public TinhTp getTinhTp() {
		return this.tinhTp;
	}

	public void setTinhTp(TinhTp tinhTp) {
		this.tinhTp = tinhTp;
	}

	@Column(name = "TEN_QUAN_HUYEN", nullable = false, length = 150)
	public String getTenQuanHuyen() {
		return this.tenQuanHuyen;
	}

	public void setTenQuanHuyen(String tenQuanHuyen) {
		this.tenQuanHuyen = tenQuanHuyen;
	}

	@Column(name = "POLYGON")
	public String getPolygon() {
		return this.polygon;
	}

	public void setPolygon(String polygon) {
		this.polygon = polygon;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quanHuyen")
	public Set<XaPhuong> getXaPhuongs() {
		return this.xaPhuongs;
	}

	public void setXaPhuongs(Set<XaPhuong> xaPhuongs) {
		this.xaPhuongs = xaPhuongs;
	}

	@Transient
	public String getTenTinhTp() {
		return tinhTp.getTenTinhTp();
	}

	@Transient
	public Integer getIdTinhTp() {
		return tinhTp.getIdTinhTp();
	}
}
