package com.dsc.qlnt.model;
// Generated Mar 27, 2021 12:16:42 AM by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TinhTp generated by hbm2java
 */
@Entity
@Table(name = "tinh_tp")
public class TinhTp implements java.io.Serializable {

	private Integer idTinhTp;
	private String tenTinhTp;
	private String polygon;
	private Set<QuanHuyen> quanHuyens = new HashSet<QuanHuyen>(0);

	public TinhTp() {
	}

	public TinhTp(String tenTinhTp) {
		this.tenTinhTp = tenTinhTp;
	}

	public TinhTp(String tenTinhTp, String polygon, Set<QuanHuyen> quanHuyens) {
		this.tenTinhTp = tenTinhTp;
		this.polygon = polygon;
		this.quanHuyens = quanHuyens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TINH_TP", unique = true, nullable = false)
	public Integer getIdTinhTp() {
		return this.idTinhTp;
	}

	public void setIdTinhTp(Integer idTinhTp) {
		this.idTinhTp = idTinhTp;
	}

	@Column(name = "TEN_TINH_TP", nullable = false, length = 150)
	public String getTenTinhTp() {
		return this.tenTinhTp;
	}

	public void setTenTinhTp(String tenTinhTp) {
		this.tenTinhTp = tenTinhTp;
	}

	@Column(name = "POLYGON")
	public String getPolygon() {
		return this.polygon;
	}

	public void setPolygon(String polygon) {
		this.polygon = polygon;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tinhTp")
	public Set<QuanHuyen> getQuanHuyens() {
		return this.quanHuyens;
	}

	public void setQuanHuyens(Set<QuanHuyen> quanHuyens) {
		this.quanHuyens = quanHuyens;
	}

	/*@Transient
	public String getMyPolygon() {
		return new String(polygon, StandardCharsets.UTF_8);
	}*/
}
