package com.dsc.qlnt.model;
// Generated Mar 27, 2021 12:16:42 AM by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TinhTrang generated by hbm2java
 */
@Entity
@Table(name = "tinh_trang")
public class TinhTrang implements java.io.Serializable {

	private int idTinhTrang;
	private String tenTinhTrang;
	private Set<PhongTro> phongTros = new HashSet<PhongTro>(0);

	public TinhTrang() {
	}

	public TinhTrang(int idTinhTrang, String tenTinhTrang) {
		this.idTinhTrang = idTinhTrang;
		this.tenTinhTrang = tenTinhTrang;
	}

	public TinhTrang(int idTinhTrang, String tenTinhTrang, Set<PhongTro> phongTros) {
		this.idTinhTrang = idTinhTrang;
		this.tenTinhTrang = tenTinhTrang;
		this.phongTros = phongTros;
	}

	@Id

	@Column(name = "ID_TINH_TRANG", unique = true, nullable = false)
	public int getIdTinhTrang() {
		return this.idTinhTrang;
	}

	public void setIdTinhTrang(int idTinhTrang) {
		this.idTinhTrang = idTinhTrang;
	}

	@Column(name = "TEN_TINH_TRANG", nullable = false, length = 50)
	public String getTenTinhTrang() {
		return this.tenTinhTrang;
	}

	public void setTenTinhTrang(String tenTinhTrang) {
		this.tenTinhTrang = tenTinhTrang;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tinhTrang")
	public Set<PhongTro> getPhongTros() {
		return this.phongTros;
	}

	public void setPhongTros(Set<PhongTro> phongTros) {
		this.phongTros = phongTros;
	}

}
