package com.dsc.qlnt.model;
// Generated Mar 27, 2021 12:16:42 AM by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * VaiTro generated by hbm2java
 */
@Entity
@Table(name = "vai_tro")
public class VaiTro implements java.io.Serializable {

	private int idVaiTro;
	private String tenVaiTro;
	private Set<NguoiDung> nguoiDungs = new HashSet<NguoiDung>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);

	public VaiTro() {
	}

	public VaiTro(int idVaiTro, String tenVaiTro) {
		this.idVaiTro = idVaiTro;
		this.tenVaiTro = tenVaiTro;
	}

	public VaiTro(int idVaiTro, String tenVaiTro, Set<NguoiDung> nguoiDungs, Set<Menu> menus) {
		this.idVaiTro = idVaiTro;
		this.tenVaiTro = tenVaiTro;
		this.nguoiDungs = nguoiDungs;
		this.menus = menus;
	}

	@Id

	@Column(name = "ID_VAI_TRO", unique = true, nullable = false)
	public int getIdVaiTro() {
		return this.idVaiTro;
	}

	public void setIdVaiTro(int idVaiTro) {
		this.idVaiTro = idVaiTro;
	}

	@Column(name = "TEN_VAI_TRO", nullable = false, length = 50)
	public String getTenVaiTro() {
		return this.tenVaiTro;
	}

	public void setTenVaiTro(String tenVaiTro) {
		this.tenVaiTro = tenVaiTro;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vaiTro")
	public Set<NguoiDung> getNguoiDungs() {
		return this.nguoiDungs;
	}

	public void setNguoiDungs(Set<NguoiDung> nguoiDungs) {
		this.nguoiDungs = nguoiDungs;
	}

	@JsonIgnore
	@OrderBy("idMenu ASC")
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "menu_vai_tro", joinColumns = {
			@JoinColumn(name = "ID_VAI_TRO", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_MENU", nullable = false, updatable = false) })
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

}
